# Generated by Django 5.0.3 on 2024-05-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
