# Generated by Django 5.0.3 on 2024-05-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_total_marks_alter_assignment_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='total_marks',
            field=models.FloatField(default=100),
        ),
    ]
